# Generated by Django 3.1.1 on 2020-11-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oranges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=100)),
                ('price1', models.IntegerField()),
                ('desc1', models.TextField()),
                ('img1', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
