# Generated by Django 3.1.1 on 2020-11-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_grapes'),
    ]

    operations = [
        migrations.CreateModel(
            name='usercontact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name3', models.CharField(max_length=100)),
                ('email3', models.EmailField(max_length=254)),
                ('comment3', models.TextField()),
            ],
        ),
    ]
